#!/bin/bash
# Check that license files are up to date
set -e
if ! git diff --exit-code --quiet third-party-licenses.*.md third-party/ 2>/dev/null; then
    echo "License files are out of date."
    exit 1
fi
echo "License check passed."
